# Generated by Django 5.2.5 on 2026-08-20 14:57

import django.core.validators
import django.db.models.deletion
import system.blocks
import system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, verbose_name="الاسم")),
                ("slug", models.SlugField(unique=True, verbose_name="المعرّف")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="السعر"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر قبل الخصم",
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        default="#b8914f", max_length=20, verbose_name="لون الباقة"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="سطر تعريفي"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "bullets",
                    models.JSONField(
                        blank=True, default=list, verbose_name="النقاط المعروضة"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="مفاتيح المزايا التي تتيحها الباقة (rsvp, countdown, gallery ...)",
                        verbose_name="المزايا المفعّلة",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="صفر = بلا حد",
                        verbose_name="أقصى عدد ضيوف",
                    ),
                ),
                (
                    "max_images",
                    models.PositiveIntegerField(default=0, verbose_name="أقصى عدد صور"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="باقة مميّزة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات والأسعار",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="رقم الهاتف",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="عنوان داخلي"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, unique=True, verbose_name="الرابط"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("review", "بانتظار المراجعة"),
                            ("published", "منشورة"),
                            ("archived", "مؤرشفة"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        default="زفاف", max_length=40, verbose_name="نوع المناسبة"
                    ),
                ),
                (
                    "name_one",
                    models.CharField(
                        default="", max_length=120, verbose_name="الاسم الأول"
                    ),
                ),
                (
                    "name_two",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="الاسم الثاني",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ ووقت المناسبة"
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="اسم القاعة"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="العنوان"
                    ),
                ),
                ("map_url", models.URLField(blank=True, verbose_name="رابط الخريطة")),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="رقم واتساب"
                    ),
                ),
                (
                    "document",
                    models.JSONField(
                        blank=True,
                        default=system.blocks.empty_document,
                        verbose_name="مستند الدعوة",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="اتركها فارغة لدعوة مفتوحة",
                        max_length=64,
                        verbose_name="كلمة سر الدعوة",
                    ),
                ),
                (
                    "public_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات"
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="system.customer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="system.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "دعوة",
                "verbose_name_plural": "الدعوات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="المجموعة"
                    ),
                ),
                (
                    "plus_ones_allowed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مرافقون مسموح بهم"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=32, unique=True, verbose_name="رمز الضيف"
                    ),
                ),
                (
                    "checked_in",
                    models.BooleanField(default=False, verbose_name="دخل القاعة"),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="ملاحظة"),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="system.invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "ضيف",
                "verbose_name_plural": "الضيوف",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RSVPResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attending", "سيحضر"),
                            ("declined", "اعتذر"),
                            ("maybe", "غير متأكد"),
                        ],
                        default="attending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "companions",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد المرافقين",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="رسالة")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="معتمدة للعرض"),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rsvps",
                        to="system.guest",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="system.invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "تأكيد حضور",
                "verbose_name_plural": "تأكيدات الحضور",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "slug",
                    models.SlugField(
                        max_length=140, unique=True, verbose_name="المعرّف"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wedding", "زفاف"),
                            ("engagement", "خطوبة"),
                            ("henna", "حنة"),
                            ("katb_ketab", "كتب كتاب"),
                            ("birthday", "عيد ميلاد"),
                            ("graduation", "تخرّج"),
                            ("aqiqah", "عقيقة"),
                            ("corporate", "مناسبة عمل"),
                            ("other", "أخرى"),
                        ],
                        default="wedding",
                        max_length=30,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        default="Premium", max_length=40, verbose_name="المجموعة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="template_covers/%Y/%m/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(blank=True, verbose_name="رابط صورة الغلاف"),
                ),
                (
                    "document",
                    models.JSONField(
                        blank=True,
                        default=system.blocks.empty_document,
                        verbose_name="مستند القالب",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("builtin", "مدمج"),
                            ("editor", "محفوظ من المحرر"),
                            ("import", "مستورد"),
                        ],
                        default="editor",
                        max_length=20,
                        verbose_name="المصدر",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="template_sources/%Y/%m/",
                        verbose_name="الملف الأصلي",
                    ),
                ),
                (
                    "required_features",
                    models.JSONField(
                        blank=True, default=list, verbose_name="المزايا التي يحتاجها"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="معروض للعملاء"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد مرات الاستخدام"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب",
                "verbose_name_plural": "القوالب",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        default="زفاف", max_length=50, verbose_name="نوع المناسبة"
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ المناسبة"
                    ),
                ),
                (
                    "names",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="أسماء أصحاب المناسبة"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="system.customer",
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order",
                        to="system.invitation",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="system.plan",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="system.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="system.template",
            ),
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=system.models._asset_path, verbose_name="الملف"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("audio", "صوت"),
                            ("video", "فيديو"),
                            ("other", "أخرى"),
                        ],
                        default="image",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم الأصلي"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="system.invitation",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="system.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف",
                "verbose_name_plural": "الملفات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["status", "-created_at"], name="system_invi_status_782599_idx"
            ),
        ),
    ]
