# Generated by Django 5.2.5 on 2026-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="bullets_en",
            field=models.JSONField(
                blank=True, default=list, verbose_name="النقاط المعروضة (EN)"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="الوصف (EN)"),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="الاسم (EN)"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="tagline_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="سطر تعريفي (EN)"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="الوصف (EN)"),
        ),
        migrations.AddField(
            model_name="template",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="الاسم (EN)"
            ),
        ),
    ]
