# Generated by Django 5.2.5 on 2026-08-21 04:50

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_plan_bullets_en_plan_description_en_plan_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="source",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=system.models._asset_path,
                verbose_name="الأصل",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="thumb",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=system.models._asset_path,
                verbose_name="مصغّرة",
            ),
        ),
    ]
