# Generated by Django 5.2.5 on 2026-08-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_template_preview_render'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم الخط')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم الإنجليزي')),
                ('family', models.CharField(help_text='اكتب اسم العائلة كما سيظهر في CSS، مثل MyFont.', max_length=120, verbose_name='اسم العائلة في CSS')),
                ('file', models.FileField(blank=True, upload_to='fonts/%Y/%m/', verbose_name='ملف الخط')),
                ('external_url', models.URLField(blank=True, help_text='اختياري — استخدمه بدلاً من رفع الملف.', verbose_name='رابط مباشر للخط')),
                ('weight', models.PositiveIntegerField(default=400, verbose_name='الوزن')),
                ('style', models.CharField(choices=[('normal', 'عادي'), ('italic', 'مائل')], default='normal', max_length=10, verbose_name='النمط')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للاستخدام')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonts_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خط مرفوع',
                'verbose_name_plural': 'مكتبة الخطوط',
                'ordering': ['order', 'name'],
            },
        ),
    ]
