# Generated by Django 5.2.5 on 2026-08-24 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_customfont'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم المفضلة')),
                ('block_type', models.CharField(max_length=60, verbose_name='نوع القسم')),
                ('block_data', models.JSONField(default=dict, verbose_name='بيانات القسم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عنصر مفضل',
                'verbose_name_plural': 'مكتبة المفضلة',
                'ordering': ['-updated_at', 'name'],
            },
        ),
    ]
