# Generated by Django 5.2.5 on 2026-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_asset_source_asset_thumb"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="music/%Y/%m/", verbose_name="الملف"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="بديل للرفع — رابط مباشر لملف صوتي.",
                        verbose_name="رابط خارجي",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ملاحظة"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="متاحة للاختيار"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "مقطوعة موسيقية",
                "verbose_name_plural": "مكتبة الموسيقى",
                "ordering": ["order", "name"],
            },
        ),
    ]
