# Generated by Django 5.2.5 on 2026-08-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_favoriteblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='runtime_scripts',
            field=models.JSONField(blank=True, default=list, verbose_name='JavaScript القالب'),
        ),
    ]
