# Generated by Django 5.2.5 on 2026-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_musictrack"),
    ]

    def _fill_pass_codes(apps, schema_editor):
        """الضيوف الموجودين قبل الميزة دي مالهمش كود.

        الحقل unique، ولو سبناهم كلهم بقيمة فاضية أول ضيفين هيصطدموا.
        """
        import secrets
        Guest = apps.get_model("system", "Guest")
        alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        used = set(Guest.objects.exclude(pass_code="")
                   .values_list("pass_code", flat=True))
        for guest in Guest.objects.filter(pass_code=""):
            while True:
                code = "FRH-" + "".join(secrets.choice(alphabet) for _ in range(6))
                if code not in used:
                    used.add(code)
                    break
            guest.pass_code = code
            # الضيوف القدام كان عندهم checked_in بس — بنحوّلها لدخلة واحدة
            guest.entries_allowed = 1 + (guest.plus_ones_allowed or 0)
            guest.entries_used = 1 if guest.checked_in else 0
            guest.save(update_fields=["pass_code", "entries_allowed", "entries_used"])

    def _noop(apps, schema_editor):
        pass

    operations = [
        migrations.CreateModel(
            name="IntroVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="intro_videos/%Y/%m/",
                        verbose_name="الفيديو",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="intro_videos/%Y/%m/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="بديل للرفع — رابط مباشر لملف فيديو.",
                        verbose_name="رابط خارجي",
                    ),
                ),
                (
                    "seconds",
                    models.FloatField(default=0, verbose_name="المدة بالثواني"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ملاحظة"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="متاح للاختيار"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "فيديو افتتاحية",
                "verbose_name_plural": "معرض الافتتاحيات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="guest",
            name="entries_allowed",
            field=models.PositiveIntegerField(
                default=1, verbose_name="عدد الدخلات المسموحة"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="entries_used",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد الدخلات المستخدمة"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="pass_code",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="كود التصريح"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="source",
            field=models.CharField(
                choices=[("manual", "مسمى"), ("rsvp", "تسجيل ذاتي")],
                default="manual",
                max_length=10,
                verbose_name="النوع",
            ),
        ),
        # التعبئة لازم تيجي **قبل** ما نفرض unique — وإلا أول ضيفين
        # قيمتهم فاضية بيصطدموا وقت الترحيل.
        migrations.RunPython(_fill_pass_codes, _noop),
        migrations.AlterField(
            model_name="guest",
            name="pass_code",
            field=models.CharField(
                blank=True, max_length=16, unique=True, verbose_name="كود التصريح"
            ),
        ),
    ]
