# Generated by Django 5.2.5 on 2026-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_template_runtime_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='runtime_root_attrs',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات غلاف JavaScript'),
        ),
    ]
