# Generated by Django 5.2.5 on 2026-08-21 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_introvideo_guest_entries_allowed_guest_entries_used_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preview_cta_enabled",
                    models.BooleanField(
                        default=True, verbose_name="شريط «عجبك القالب؟»"
                    ),
                ),
                (
                    "preview_cta_text",
                    models.CharField(
                        default="عجبك القالب ده؟", max_length=120, verbose_name="النص"
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(default=True, verbose_name="إظهار واتساب"),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="بالكود الدولي، مثال: +201559403203",
                        max_length=30,
                        verbose_name="رقم الواتساب",
                    ),
                ),
                (
                    "whatsapp_message",
                    models.CharField(
                        default="السلام عليكم، عايز أطلب دعوة بقالب: {template}",
                        help_text="{template} بتتبدّل باسم القالب اللي الزائر شايفه.",
                        max_length=300,
                        verbose_name="الرسالة الجاهزة",
                    ),
                ),
                (
                    "facebook_enabled",
                    models.BooleanField(default=True, verbose_name="إظهار فيسبوك"),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="رابط صفحة فيسبوك"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
        migrations.CreateModel(
            name="PlanAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="الاسم (EN)"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="اختياري — مفتاح ميزة في المحرك (music / rsvp / gallery …). لو اتحط، شراء الإضافة بيفتح الميزة في الدعوة.",
                        max_length=40,
                        verbose_name="مفتاح الميزة",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="السعر",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="وصف مختصر"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="سيبها فاضية عشان الإضافة تظهر مع كل الباقات.",
                        related_name="addons",
                        to="system.plan",
                        verbose_name="الباقات",
                    ),
                ),
            ],
            options={
                "verbose_name": "إضافة",
                "verbose_name_plural": "الإضافات",
                "ordering": ["sort_order", "price", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrderAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="الاسم وقت الشراء"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="السعر وقت الشراء",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_addons",
                        to="system.order",
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_addons",
                        to="system.planaddon",
                    ),
                ),
            ],
            options={
                "verbose_name": "إضافة الطلب",
                "verbose_name_plural": "إضافات الطلب",
                "unique_together": {("order", "addon")},
            },
        ),
    ]
