# Generated by Django 5.2.5 on 2026-08-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_template_runtime_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_ar', models.CharField(max_length=240, verbose_name='السؤال بالعربية')),
                ('answer_ar', models.TextField(verbose_name='الإجابة بالعربية')),
                ('question_en', models.CharField(blank=True, max_length=240, verbose_name='السؤال بالإنجليزية')),
                ('answer_en', models.TextField(blank=True, verbose_name='الإجابة بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_enabled',
            field=models.BooleanField(default=True, verbose_name='إظهار إنستجرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='رابط إنستجرام'),
        ),
    ]
