# Generated by Django 5.2.5 on 2026-08-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_sitesetting_planaddon_orderaddon"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="orders_enabled",
            field=models.BooleanField(
                default=True,
                help_text="اقفله لو بتاخد الطلبات على واتساب. القسم بيختفي من الصفحة، وأزرار «اطلب دعوتك» بتوجّه على واتساب، والسيرفر بيرفض أي إرسال للنموذج — مش بيتخبّى بس.",
                verbose_name="نموذج «اطلب دعوتك» في الموقع",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="whatsapp_cta_message",
            field=models.CharField(
                blank=True,
                default="السلام عليكم، حابب أستفسر عن الدعوات الرقمية",
                help_text="الرسالة الجاهزة اللي هتتكتب للزائر لما يدوس الأيقونة. دي غير رسالة شريط «عجبك القالب؟» اللي فيها {template}.",
                max_length=300,
                verbose_name="رسالة الزر العائم",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="whatsapp_float_enabled",
            field=models.BooleanField(
                default=True,
                help_text="أيقونة واتساب ثابتة في ركن كل صفحات الموقع. محتاجة «رقم الواتساب» تحت.",
                verbose_name="زر واتساب عائم في الموقع",
            ),
        ),
    ]
