# Generated by Django 5.2.5 on 2026-08-25 20:58

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_faq_sitesetting_instagram_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='client_token',
            field=models.CharField(db_index=True, default=system.models._new_client_token, editable=False, max_length=40, unique=True, verbose_name='رمز رابط العميل'),
        ),
    ]
